export const cols = [
  { label: 'Nome', row: 'name' },
  { label: 'E-mail', row: 'email' },
  { label: 'Idade', row: 'age', hasTotal: true },
  { label: 'Malícia', row: 'malice', hasTotal: true }
]

export const rows = [
  { name: 'coe1', email: 'coe1.mane@gmail.com', age: 6 },
  { name: 'coe2', email: 'coe2.mane@gmail.com', age: 3, malice: 3 },
  { name: 'coe3', email: 'coe3.mane@gmail.com', age: 2 },
  { name: 'coe4', email: 'coe4.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe5', email: 'coe5.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe6', email: 'coe6.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe7', email: 'coe7.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe8', email: 'coe8.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe9', email: 'coe9.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe10', email: 'coe10.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe11', email: 'coe11.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe12', email: 'coe12.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe13', email: 'coe13.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe14', email: 'coe14.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe15', email: 'coe15.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe16', email: 'coe16.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe17', email: 'coe17.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe18', email: 'coe18.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe19', email: 'coe19.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe20', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe21', email: 'coe21.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe22', email: 'coe22.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe22', email: 'coe22.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe23', email: 'coe23.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe24', email: 'coe24.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe25', email: 'coe25.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe26', email: 'coe26.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe27', email: 'coe27.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe28', email: 'coe28.mane@gmail.com', age: 2, malice: 20 },
  { name: 'coe29', email: 'coe29.mane@gmail.com', age: 2, malice: 10 },
  { name: 'coe30', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe31', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe32', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe33', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe34', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe34', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe35', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe36', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe37', email: 'coe20.mane@gmail.com', age: 1, malice: 10 },
  { name: 'coe38', email: 'coe20.mane@gmail.com', age: 1, malice: 10 }
]

export const total = { label: 'Total', colPosition: 'email' }
